version: '3.8'
services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    ports:
      - "3310:3306"
    volumes:
      - ./mysql-data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: service123
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak123
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.4
    command: ["start-dev"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_PASSWORD: keycloak123
      DB_PORT: 3310
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./mysql-data:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
